//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Store.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class routine
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<short> dayofweek { get; set; }
        public Nullable<System.DateTime> workfrom { get; set; }
        public Nullable<System.DateTime> workto { get; set; }
        public Nullable<System.DateTime> intervalfrom { get; set; }
        public Nullable<System.DateTime> intervalto { get; set; }
    
        public virtual pn_daynames pn_daynames { get; set; }
    }
}
